# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba966a414917e1df0fe150c6fed28982b3985943efeeb8c71d274a3db5452e1ea5e06ba6b80e2c93014a3e749bb1051c63017e12fc8844ac01c58616aa3cb128

test:
  secret_key_base: 2d8b5ea2f4b8da277f8745410b90e778e1554a7e373792b8c84d3a527608875958630e6caa60e22800638653a5f750cb4dff44e7aae16f54252d626ff37882e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
